#!/usr/bin/env bash

couchDbInitIndicator=/opt/couchdb/lib/couchdb-not-inited

if [[ -e $couchDbInitIndicator ]]; then
  echo "Initialising CouchDB..."
  initialise_couchdb
  rm -f $couchDbInitIndicator
fi

echo "Starting CouchDB..."
/opt/couchdb/bin/couchdb

exit 0
